# Generated by Django 3.0.8 on 2020-07-26 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def forward_func(apps,schema_editor):
    # 현재 모든 User에 대해서 Profile을 만들어준다.

    auth_user_model = settings.AUTH_USER_MODEL.split('.') # settings.AUTH_USER_MODEL 의 값은 원래 'auth.User' 이다. 하지만 split으로 튜플로만들어줌
    # User = apps.get_model("auth","User")
    # User = apps.get_model(auth_user_model[0],auth_user_model[1])
    User = apps.get_model(*auth_user_model) # 언패킹
    Profile = apps.get_model('accounts','Profile')
    
    for user in User.objects.all():
        print('create profile for user#{}'.format(user.pk))
        Profile.objects.create(user=user)

def backward_func(apps,schema_editor):
    pass

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(forward_func,backward_func), # 테이블이 만들어지자마자 forward_func 호출
    ]
